### ISSUE TITLE
possible to not set environment for cucumber

### ISSUE THREAD

**Issue by jsmestad** [ngauthier/hydra#27]
Is it possible to set RAILS_ENV=cucumber without specifying it every time in the command line? If I do not specify it tells me its running in development mode.

**Comment by ngauthier** [comment]
During cucumber's normal execution (non-hydra) it sets up the environment for you. However, hydra runs them in a different way from the standard cucumber binary, and it does not assume any environments on your behalf.

This is because often there are hybrid test suites that run cucumber and other frameworks, which may require different environments. So, you do have to specify the environment every time.

You could create a rake task that sets the env to cucumber. Then have the hydra task depend on that rake task. That way every time you run it, your own task will set it up for you.
