### ISSUE TITLE
Hydra depends on test::unit and is not compatible with ruby 1.9 and minitest

### ISSUE THREAD

**Issue by hedgehog** [ngauthier/hydra#29]
hydra-0.23.1 requires the gem "test-unit" - could this be broken out in some way?

I see this in a Rakefile that loads libs using Bundler.require(...)

```
+no such file to load -- test/unit/testresult
+/home/hedge/.rvm/gems/ruby-1.9.2-p0@fog/gems/hydra-0.23.1/lib/hydra/runner.rb:2:in `require'
+/home/hedge/.rvm/gems/ruby-1.9.2-p0@fog/gems/hydra-0.23.1/lib/hydra/runner.rb:2:in `<top (required)>'
+/home/hedge/.rvm/gems/ruby-1.9.2-p0@fog/gems/hydra-0.23.1/lib/hydra.rb:7:in `require'
+/home/hedge/.rvm/gems/ruby-1.9.2-p0@fog/gems/hydra-0.23.1/lib/hydra.rb:7:in `<top (required)>'
```

**Comment by ngauthier** [comment]
hey hedgehog,

There is a lot more that needs to happen to get hydra to ruby 1.9.2, so breaking test/unit out wouldn't help you all that much. Sorry :-(

If you're interested in trying to do it yourself, please feel free to ask me any questions concerning the steps needed to make hydra 1.9 compatible.

**Comment by hedgehog** [comment]
Okay, but listing this gem in the gemspec is an easy start ;)
1.9.x is an itch I'd like to scratch from time to time.

Any chance of Hydra gurus creating some vip '1.9.x issues', so that people can gather around?
Or is spec coverage sufficiently good that we can just run those to see which loc are broken?  Will look.  But would be nice to get some deeper insight into the scope of the task TIA

**Comment by ngauthier** [comment]
since hydra uses test unit internals to run tests in parallel, hydra's test unit runner will have to be re-written to use minitest internals to run them in parallel.

The specs are good enough that you can use them to see if your test runner is working or not. They test functionality and concurrency.

We can leave this issue open to point out the 1.9 issues w/ hydra.

**Comment by hedgehog** [comment]
Okay thanks - I ran into the issue because even though I used nothing from /test/minitest etc. I got an exception on some hydra require - since I don't have any 'test' libs in this gemset it puzzled - hence the report - I haven't started to use hydra in anger yet.

I think issues can't be re-opened so maybe I can open issues for each spec/scenario/whatever you use - when I get to running them that is...?
A 1.9.x label would be useful?

**Comment by ngauthier** [comment]
Hey I think you're a bit confused on the issue here. Hydra does not depend on test unit. I runs test unit tests for you. But when ruby 1.8 went to 1.9, the internals of test unit were switched to minitest.

So, hydra's overrides on test/unit are breaking because the classes no longer exist. So it's not a gemspec/dependency issue, it's a ruby 1.9 incompatibility issue.

I'll reopen the issue and mark it ruby1.9.

**Comment by hedgehog** [comment]
Okay, thanks for the patience - I was just at the point of entering some rake tasks.

**Comment by ngauthier** [comment]
if you are interested in hacking in the minitest concurrency, check out this patch of mine to minitest which adds a parallel command line argument. Should show you how to get started if you want to do it:

https://github.com/ngauthier/minitest/commit/edc756999ae6fded3c825bf43baa4a53dde4d1ef

**Comment by hedgehog** [comment]
Actually rspec + cucumber are more my interest - It looks hydra eats its own test-dogfood.
Would it make sense, i.e. be acceptable, to replicate this with cucumber and rspec?  Or do you prefer that rspec/cucmber behavior/issues be exposed and resolved outside of Hydra's source.  I appreciate there is some risk of the tests suites getting out of sync and so getting a spurious/undeserved reputation as second class citizen - but no worse than having on specs/features present.

**Comment by ngauthier** [comment]
hydra doesn't dog food it's own suite. It uses basic T::U and shoulda.

I have been interested in breaking out the cucumber/rspec/jslint/T::U runners into pluggable modules so that people can mix in their own frameworks more easily. However I have not gotten around to it.

**Comment by coffeencoke** [comment]
We would love to use this, but must wait for 1.9.2 support. Is there anyone working on this? Maybe we can help?

**Comment by ngauthier** [comment]
Hydra needs to have it's runner re-written to make it more plug-and-play for frameworks. So it's a larger undertaking.

I've been focusing more on making test frameworks support multi-threading themselves. For example, I have an early project for 1.9.2 that can run minitest suites in parallel:

https://github.com/ngauthier/minitest-parallel

But that's not ready to be released yet.

If you'd like to fork hydra and make it work for 1.9.2 (which would break 1.8.7 support) then at least when I (or someone else) re-writes the runner, we can use your fork for when we do 1.9.2 stuff.

The difficulty with a plug-and-play framework system is that the distributed workers also need to be told which frameworks to use. I'd like to have it so that you can specify if you're using rspec 1 or 2, cucumber versions, ruby 1.8 or 1.9 (T::U / MiniTest).

If you work on any of these things, let me know, and we can put some references to forks in the wiki for specific versions in the short-term.

**Comment by pjammer** [comment]
if i may suggest, maybe you could say something about it being 1.8 only in the readme.
