### ISSUE TITLE
Seperate databases per runner

### ISSUE THREAD

**Issue by trobrock** [ngauthier/hydra#43]
Is there any way to use a different database per runner process?

**Comment by ngauthier** [comment]
yes, you can define a 'hydra_worker_init.rb' file and put in any code you want. This will get run when a worker boots.

https://github.com/ngauthier/hydra/blob/master/lib/hydra/worker.rb#L35

Because hydra is written for ruby (not necessarily rails) it does not contain any rails-specific code, so it is up to you to write it.

Also, give parallel_tests a shot if you have trouble with hydra. It's not as fast, but it's more robust.

**Comment by trobrock** [comment]
Awesome great thanks. I looked at parallel_tests a little while back, and so far am having much better success with Hydra

**Comment by ngauthier** [comment]
Cool great to hear. If you have a lot of success, please post a success
story in the wiki. It makes me feel warm and fuzzy.
